---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install node js"
  become: yes
  apt:
    name: nodejs

- name: "install npm"
  become: true
  apt:
    name: npm

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes

- name: "Set Environment Variables"
  environment:
    ENVIRONMENT: 'production'
    TYPEORM_CONNECTION: 'postgres'
    TYPEORM_ENTITIES: './src/modules/domain/**/*.entity.ts'
    TYPEORM_HOST: 'database-1.cu2h5ixhgjsu.us-east-1.rds.amazonaws.com'
    TYPEORM_PORT: '5432'
    TYPEORM_USERNAME: 'postgres'
    TYPEORM_PASSWORD: 'VMware1!'
    TYPEORM_DATABASE: 'database-1'