---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install node js"
  become: yes
  apt:
    name: nodejs
    status: present

- name: "install npm"
  become: true
  apt:
    name: npm
    status: present

- name: "install pm2"
  become: true
  npm:
    name: pm2
    state: present